### ISSUE TITLE
extract the learned graph structure from the trained GKT model

### ISSUE THREAD

**Issue by KumiXH** [jhljx/GKT#4]
Hello, I don't understand how to extract the learned graph structure. I haven't found relevant information in the code
![image](https://user-images.githubusercontent.com/46064049/167809570-3957fee2-9b20-4bfe-ac86-d412db4d9839.png)

**Comment by alexis-delaunay** [comment]
Hey! Did you found a way to extract the graph structure somehow? @KumiXH

**Comment by jhljx** [comment]
I don't know, too. Maybe you can contact the author. I only implement this method based on my own knowledge.

**Comment by AMJasser** [comment]
@KumiXH Did you find a way to extract the graph structure?

**Comment by KumiXH** [comment]
sry,I can't find it @AMJasser
