### ISSUE TITLE
Answers from raw data are not shifted by 1

### ISSUE THREAD

**Issue by Chen-Yiyang** [jhljx/GKT#5]
First of all, I would like to thank you for implementing the codebase in such an efficient and comprehensive way!

Just one minor issue that I have noticed that in `processing.py` as you are converting raw data from CSV files to answers, questions, and features, you mention in [comments](https://github.com/jhljx/GKT/blob/271c72dda6aba454a07c9eeb7fc238f145ac0765/processing.py#L85) that in Step 4, answers need to be shifted by 1, which I think is in line with the problem definition and the paper. However, I don't think there are any shift operations been done in preparing the raw data, nor is there any operation that does this when iterating the dataloader.

So I would like to know whether there is anything that I overlooked, or this is indeed a typo in the codebase.

Thank you!

Below is the code snippet for Step 4 from the file.
```Python
    # Step 4 - Convert to a sequence per user id and shift features 1 timestep
    feature_list = []
    question_list = []
    answer_list = []
    seq_len_list = []
```

**Comment by jhljx** [comment]
This comment is consistent with another repository https://github.com/lccasagrande/Deep-Knowledge-Tracing/blob/master/deepkt/data_util.py. I think shifting by 1 aims to use the current item x(t) to predict the next item x(t+1).
